### ISSUE TITLE
Programmed frameshift example

### ISSUE THREAD

**Issue by nathanweeks** [The-Sequence-Ontology/Specifications#10]
For the CDS features in the _Programmed frameshift_ example:

```
chrX  . CDS                XXXX   YYYY 0  +  . ID=cds01;Parent=tran01
chrX  . CDS                YYYY-1 ZZZZ 1  +  . ID=cds01;Parent=tran01
```

Is it intended for the "0" and "1" to be in the _phase_ (8th) column, rather than the _score_ (6th) column? i.e.:

```
chrX  . CDS                XXXX   YYYY .  +  0 ID=cds01;Parent=tran01
chrX  . CDS                YYYY-1 ZZZZ .  +  1 ID=cds01;Parent=tran01
```

**Comment by barrymoore** [comment]
Thanks @nathanweeks for catching this type.  I've updated the spec to correct the issue here:

https://github.com/The-Sequence-Ontology/Specifications/commit/da5cfd12c0948a29c9d8a6966aed7bfe186792a8
