### ISSUE TITLE
Clarification on the use of the sequence region directive.

### ISSUE THREAD

**Issue by darcyabjones** [The-Sequence-Ontology/Specifications#22]
Hi there!

We've recently encountered an issue while sharing GFF3 files with colleagues using [Geneous](https://www.geneious.com/).
I'm piecing this together from my colleague's interactions with geneous support, but seems that including `## sequence-region` lines with a start coordinate > 1 will affect how they display features or extract sequences.
I suspect they've interpreted it as an offset rather than a boundary check thing as I had interpreted it.

We typically use [genometools](http://genometools.org/) to process/tidy GFF3 files, which automatically adds these lines based on the min and max coordinate in the file.

What is the correct way to specify these lines?
Should we just be setting the start and end to be 1 and the sequence length?

Thanks in advance!

Darcy

**Comment by keilbeck** [comment]
@barrymoore @srynobio Can either of you throw some light on this issue? thanks.

**Comment by darcyabjones** [comment]
I've noticed now that this is covered in the `##sequence-region seqid start end` section of the GFF3 spec.
I'll finally get around to bugging the Geneous people about it.

Thanks
