### ISSUE TITLE
Broken links to GFF3 specifcation.

### ISSUE THREAD

**Issue by diekhans** [The-Sequence-Ontology/Specifications#3]
Moving the location of the GFF3 specification has broken a web of links to this file.    Can
you please add a redirect to fix the links.

Normally, I wouldn't file a bug report rather contact the web site admin, however 
the links to the contacts is broken:

  http://www.sequenceontology.org/?page_id=259

http://www.sequenceontology.org/contacts/

**Comment by srynobio** [comment]
All the link on that page are now working correctly.  Thanks for letting us know @diekhans 

@keilbeck you might want to check the content to make sure it up to date.
