### ISSUE TITLE
Precision about the 9th column

### ISSUE THREAD

**Issue by Juke34** [The-Sequence-Ontology/Specifications#6]
In my sense, it should be clearly stipulated since the "Column 9: "attributes" paragraph when the ID tag is mentioned that the ID attributes are only mandatory for features that have children. (And similarly with the Parent...).

It only mentioned later within the text "The ID attributes are only mandatory for those features that have children".

**Comment by barrymoore** [comment]
Thanks @Juke34 I've addressed your proposed update here:

https://github.com/The-Sequence-Ontology/Specifications/commit/41b7358e2d7832c11ac712648b27f8528912c39f
